/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculo;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author levia
 */
public class CalculoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculoJFrame
     */
    public CalculoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        btnQ1 = new javax.swing.JButton();
        btnQ2 = new javax.swing.JButton();
        btnQ3 = new javax.swing.JButton();
        btnQ4 = new javax.swing.JButton();
        btnQ5 = new javax.swing.JButton();
        enunciadoPanel = new javax.swing.JPanel();
        q1Label = new javax.swing.JLabel();
        q2Label = new javax.swing.JLabel();
        q3Label = new javax.swing.JLabel();
        q4Label = new javax.swing.JLabel();
        q5Label = new javax.swing.JLabel();
        respostaPanel = new javax.swing.JPanel();
        q1RespostaLabel = new javax.swing.JLabel();
        topoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 768));

        principalPanel.setBackground(new java.awt.Color(204, 204, 204));
        principalPanel.setMinimumSize(new java.awt.Dimension(1000, 760));
        principalPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQ1.setText("Questão 1");
        btnQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ1ActionPerformed(evt);
            }
        });
        principalPanel.add(btnQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        btnQ2.setText("Questão 2");
        btnQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ2ActionPerformed(evt);
            }
        });
        principalPanel.add(btnQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        btnQ3.setText("Questão 3");
        btnQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ3ActionPerformed(evt);
            }
        });
        principalPanel.add(btnQ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        btnQ4.setText("Questão 4");
        btnQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ4ActionPerformed(evt);
            }
        });
        principalPanel.add(btnQ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        btnQ5.setText("Questão 5");
        btnQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ5ActionPerformed(evt);
            }
        });
        principalPanel.add(btnQ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        enunciadoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout enunciadoPanelLayout = new javax.swing.GroupLayout(enunciadoPanel);
        enunciadoPanel.setLayout(enunciadoPanelLayout);
        enunciadoPanelLayout.setHorizontalGroup(
            enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q2Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q3Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q4Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q5Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q1Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        enunciadoPanelLayout.setVerticalGroup(
            enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q2Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q3Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q4Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q5Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(enunciadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(enunciadoPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(q1Label)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        principalPanel.add(enunciadoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 480, 560));

        respostaPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout respostaPanelLayout = new javax.swing.GroupLayout(respostaPanel);
        respostaPanel.setLayout(respostaPanelLayout);
        respostaPanelLayout.setHorizontalGroup(
            respostaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respostaPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(q1RespostaLabel)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        respostaPanelLayout.setVerticalGroup(
            respostaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(respostaPanelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(q1RespostaLabel)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        principalPanel.add(respostaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 400, 560));

        topoPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Enunciado");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Resposta");

        javax.swing.GroupLayout topoPanelLayout = new javax.swing.GroupLayout(topoPanel);
        topoPanel.setLayout(topoPanelLayout);
        topoPanelLayout.setHorizontalGroup(
            topoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(144, 144, 144))
        );
        topoPanelLayout.setVerticalGroup(
            topoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principalPanel.add(topoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ5ActionPerformed
        q1Label.setIcon(null);
        q2Label.setIcon(null);
        q3Label.setIcon(null);
        q4Label.setIcon(null);
        q2Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\levia\\OneDrive\\Documentos\\NetBeansProjects\\CalculoNumerico\\src\\main\\java\\calculo\\q5.png"));
    }//GEN-LAST:event_btnQ5ActionPerformed

    private void btnQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ4ActionPerformed
        q1Label.setIcon(null);
        q2Label.setIcon(null);
        q3Label.setIcon(null);
        q5Label.setIcon(null);
        q4Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\levia\\OneDrive\\Documentos\\NetBeansProjects\\CalculoNumerico\\src\\main\\java\\calculo\\q4.png"));
    }//GEN-LAST:event_btnQ4ActionPerformed

    private void btnQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ3ActionPerformed
        // TODO add your handling code here:
        q1Label.setIcon(null);
        q2Label.setIcon(null);
        q4Label.setIcon(null);
        q5Label.setIcon(null);
        q3Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\levia\\OneDrive\\Documentos\\NetBeansProjects\\CalculoNumerico\\src\\main\\java\\calculo\\q3.png"));
    }//GEN-LAST:event_btnQ3ActionPerformed

    private void btnQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ2ActionPerformed
        q1Label.setIcon(null);
        q3Label.setIcon(null);
        q4Label.setIcon(null);
        q5Label.setIcon(null);
        q2Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\levia\\OneDrive\\Documentos\\NetBeansProjects\\CalculoNumerico\\src\\main\\java\\calculo\\q2.png"));
    }//GEN-LAST:event_btnQ2ActionPerformed

    private void btnQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ1ActionPerformed
        q2Label.setIcon(null);
        q3Label.setIcon(null);
        q4Label.setIcon(null);
        q5Label.setIcon(null);
        q1Label.setIcon(new javax.swing.ImageIcon("C:\\Users\\levia\\OneDrive\\Documentos\\NetBeansProjects\\CalculoNumerico\\src\\main\\java\\calculo\\q1.png"));
    }//GEN-LAST:event_btnQ1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoJFrame().setVisible(true);
            }
        });
    }
    public static double q1(){
        double a, a0 = 40, fa, b, b0 = 90, fb, x, x0 = 65, y, erro;
        a = a0;
        b = b0;
        do{           
            fa = (a - a * Math.pow(Math.E, (-135/a)) - 53.03);
            fb = (b - b * Math.pow(Math.E, (-135/b)) - 53.03);
            y = (x0 - x0 * Math.pow(Math.E, (-135/x0)) - 53.03);
            a = ((fa >= 0 && y >= 0) || (fa < 0 && y < 0)) ? x0 : a;
            b = ((fb >= 0 && y >= 0) || (fb < 0 && y < 0)) ? x0 : b;
            x = (a + b) / 2;
            erro = Math.abs(x - x0);
            x0 = x;
	}while(erro > 0.1);
        return x;
    }
    public static double q2(){
        double x0 = 1, y, dy, x, erro;
        do{           
            y = 18.18 * Math.pow(x0, 2) - 2.1 * x0 - 30;
            dy = 36.36 * x0 - 2.1;
            x = x0 - (y/dy);
            erro = Math.abs(x - x0);
            x0 = x;
	}while(erro > 0.01);
        return x;
    }
    public static double[] q3(){
        double x, x0, y, y0, f, g, fy, fx, gy, gx, errox, erroy, detx, dety, detd;
        double[] resultado = new double[2];
        x0 = 2.3;
        y0 = 5;
        fy = 1;
        gy = -1;
        do{
            f = y0 - 10 + Math.pow(x0, 2);
            g = 15 - Math.pow(Math.E, x0) - y0;
            fx = 2*x0;
            gx = - Math.pow(Math.E, x0);
            detx = det(f, fy, g, gy);
            dety = det(fx, f, gx, g);
            detd = det(fx, fy, gx, gy);
            x = x0 - detx/detd;
            y = y0 - dety/detd;
            errox = Math.abs(x - x0);
            erroy = Math.abs(y - y0);
            x0 = x;
            y0 = y;
        }while((errox > 0.01) && (erroy > 0.01));
        resultado[0] = x;
        resultado[1] = y;
        return resultado;
    }
    public static double det(double a, double b, double c, double d){
        
        return (a*d-b*c);
    }
    public static double q4(){
        double a, a0 = -2, fa, b, b0 = 0, fb, x, x0 = -1, y, erro;
        a = a0;
        b = b0;
        do{           
            fa = (2 * Math.cos(a) - Math.pow(Math.E, a)/2);
            fb = (2 * Math.cos(b) - Math.pow(Math.E, b)/2);
            y = (2 * Math.cos(x0) - Math.pow(Math.E, x0)/2);
            a = ((fa >= 0 && y >= 0) || (fa < 0 && y < 0)) ? x0 : a;
            b = ((fb >= 0 && y >= 0) || (fb < 0 && y < 0)) ? x0 : b;
            x = (a + b) / 2;
            erro = Math.abs(x - x0);
            x0 = x;
	}while(erro > 0.1);
        return x;
    }
    public static double q5(){
        double x0 = 2, y, dy, x, erro;
        do{           
            y = Math.log(x0) - 0.5;
            dy = 1/x0;
            x = x0 - (y/dy);
            erro = Math.abs(x - x0);
            x0 = x;
	}while(erro > 0.01);
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQ1;
    private javax.swing.JButton btnQ2;
    private javax.swing.JButton btnQ3;
    private javax.swing.JButton btnQ4;
    private javax.swing.JButton btnQ5;
    private javax.swing.JPanel enunciadoPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JLabel q1Label;
    private javax.swing.JLabel q1RespostaLabel;
    private javax.swing.JLabel q2Label;
    private javax.swing.JLabel q3Label;
    private javax.swing.JLabel q4Label;
    private javax.swing.JLabel q5Label;
    private javax.swing.JPanel respostaPanel;
    private javax.swing.JPanel topoPanel;
    // End of variables declaration//GEN-END:variables
}
